name: Bugiver
description: A small site that gives you an issue to fix when there is nothing to do.
client_id: 8a518f3373e19665e2b0
storage_id: bugiver
links:
  - name: GitHub
    icon: https://github.com/favicon.ico
    url: https://jfenn.me/redirects/?t=github&d=bugiver
  - name: Apache 2.0 License
    icon: /images/ic/copyright.svg
    url: https://choosealicense.com/licenses/apache-2.0
contributors:
  - login: TheAndroidMaster
    avatar: https://avatars1.githubusercontent.com/u/13000407?v=4
    url: https://github.com/TheAndroidMaster
deps:
  - name: ShowdownJS
    icon: http://showdownjs.com/favicon.ico
    url: http://showdownjs.com/
